spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    com.aivle13: INFO

management:
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true