spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  flyway:
    enabled: false

logging:
  level:
    com.aivle13: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"