--
-- PostgreSQL database dump
--



--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- Name: ai_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_models (
                                  is_high_impact boolean,
                                  created_at timestamp(6) without time zone NOT NULL,
                                  model_id bigint NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL,
                                  user_id bigint NOT NULL,
                                  domain character varying(20) NOT NULL,
                                  model_type character varying(20) NOT NULL,
                                  status character varying(20) NOT NULL,
                                  version character varying(20) NOT NULL,
                                  model_group_id character varying(36) NOT NULL,
                                  model_name character varying(100) NOT NULL,
                                  artifact_path character varying(255) NOT NULL,
                                  original_file_name character varying(255),
                                  CONSTRAINT ai_models_domain_check CHECK (((domain)::text = ANY ((ARRAY['CREDIT_SCORING'::character varying, 'CREDIT_LIMIT'::character varying])::text[]))),
                                  CONSTRAINT ai_models_model_type_check CHECK (((model_type)::text = ANY ((ARRAY['XGBOOST'::character varying, 'LOGISTIC'::character varying, 'LIGHTGBM'::character varying])::text[]))),
                                  CONSTRAINT ai_models_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: ai_models_model_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_models ALTER COLUMN model_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_models_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: audit_law_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_law_mappings (
                                           article_id bigint NOT NULL,
                                           audit_id bigint NOT NULL,
                                           mapping_id bigint NOT NULL,
                                           compliance character varying(20) NOT NULL,
                                           evidence text,
                                           CONSTRAINT audit_law_mappings_compliance_check CHECK (((compliance)::text = ANY ((ARRAY['COMPLIANT'::character varying, 'NON_COMPLIANT'::character varying, 'PENDING'::character varying])::text[])))
);


--
-- Name: audit_law_mappings_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_law_mappings ALTER COLUMN mapping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_law_mappings_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: audits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audits (
                               current_step integer NOT NULL,
                               manual_threshold numeric(5,4),
                               model_accuracy numeric(6,4),
                               model_auc numeric(6,4),
                               retention_until date,
                               target_approval_rate numeric(5,4),
                               assessment_id bigint,
                               audit_id bigint NOT NULL,
                               completed_at timestamp(6) without time zone,
                               created_at timestamp(6) without time zone NOT NULL,
                               dataset_id bigint NOT NULL,
                               model_id bigint NOT NULL,
                               updated_at timestamp(6) without time zone NOT NULL,
                               user_id bigint NOT NULL,
                               validation_dataset_id bigint,
                               status character varying(20) NOT NULL,
                               threshold_method character varying(20) NOT NULL,
                               audit_name character varying(100) NOT NULL,
                               sensitive_features character varying(255) NOT NULL,
                               generation integer DEFAULT 0 NOT NULL,
                               CONSTRAINT audits_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLIANT'::character varying, 'WARNING'::character varying, 'NON_COMPLIANT'::character varying, 'UNCONFIRMED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
                               CONSTRAINT audits_threshold_method_check CHECK (((threshold_method)::text = ANY ((ARRAY['VALIDATION_DATASET'::character varying, 'MANUAL'::character varying])::text[])))
);


--
-- Name: audits_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audits ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audits_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: board_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_comments (
                                       author_id bigint NOT NULL,
                                       comment_id bigint NOT NULL,
                                       created_at timestamp(6) without time zone NOT NULL,
                                       post_id bigint NOT NULL,
                                       updated_at timestamp(6) without time zone NOT NULL,
                                       content text NOT NULL
);


--
-- Name: board_comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_comments ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_comments_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: board_post_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_post_attachments (
                                               attachment_id bigint NOT NULL,
                                               created_at timestamp(6) without time zone NOT NULL,
                                               post_id bigint NOT NULL,
                                               size bigint NOT NULL,
                                               updated_at timestamp(6) without time zone NOT NULL,
                                               content_type character varying(100),
                                               file_key character varying(512) NOT NULL,
                                               original_name character varying(255) NOT NULL
);


--
-- Name: board_post_attachments_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_post_attachments ALTER COLUMN attachment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_post_attachments_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: board_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_posts (
                                    pinned boolean NOT NULL,
                                    author_id bigint NOT NULL,
                                    created_at timestamp(6) without time zone NOT NULL,
                                    post_id bigint NOT NULL,
                                    updated_at timestamp(6) without time zone NOT NULL,
                                    title character varying(200) NOT NULL,
                                    content text NOT NULL
);


--
-- Name: board_posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_posts ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_posts_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: chat_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_conversations (
                                           audit_id bigint NOT NULL,
                                           conversation_id bigint NOT NULL,
                                           created_at timestamp(6) without time zone NOT NULL,
                                           updated_at timestamp(6) without time zone NOT NULL,
                                           user_id bigint NOT NULL,
                                           title character varying(100) NOT NULL
);


--
-- Name: chat_conversations_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_conversations ALTER COLUMN conversation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_conversations_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: chat_message_citations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_message_citations (
                                               similarity numeric(6,4),
                                               citation_id bigint NOT NULL,
                                               created_at timestamp(6) without time zone NOT NULL,
                                               message_id bigint NOT NULL,
                                               updated_at timestamp(6) without time zone NOT NULL,
                                               citation_type character varying(20) NOT NULL,
                                               source_url character varying(500),
                                               reference character varying(255) NOT NULL,
                                               snippet character varying(255),
                                               CONSTRAINT chat_message_citations_citation_type_check CHECK (((citation_type)::text = ANY ((ARRAY['AUDIT_METRIC'::character varying, 'GROUP_STAT'::character varying, 'LAW_ARTICLE'::character varying, 'REPORT_SECTION'::character varying])::text[])))
);


--
-- Name: chat_message_citations_citation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_message_citations ALTER COLUMN citation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_citations_citation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
                                      conversation_id bigint NOT NULL,
                                      created_at timestamp(6) without time zone NOT NULL,
                                      message_id bigint NOT NULL,
                                      updated_at timestamp(6) without time zone NOT NULL,
                                      grounding_status character varying(20),
                                      role character varying(20) NOT NULL,
                                      content text NOT NULL,
                                      CONSTRAINT chat_messages_grounding_status_check CHECK (((grounding_status)::text = ANY ((ARRAY['GROUNDED'::character varying, 'PARTIAL'::character varying, 'NOT_GROUNDED'::character varying])::text[]))),
                                      CONSTRAINT chat_messages_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ASSISTANT'::character varying])::text[])))
);


--
-- Name: chat_messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: datasets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.datasets (
                                 audited boolean NOT NULL,
                                 row_count integer NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 dataset_id bigint NOT NULL,
                                 model_id bigint NOT NULL,
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 data_source character varying(20) NOT NULL,
                                 purpose character varying(20) NOT NULL,
                                 columns text NOT NULL,
                                 dataset_file_key character varying(255),
                                 original_file_name character varying(255),
                                 sensitive_attributes text,
                                 CONSTRAINT datasets_data_source_check CHECK (((data_source)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'DUMMY'::character varying])::text[]))),
                                 CONSTRAINT datasets_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['AUDIT'::character varying, 'VALIDATION'::character varying])::text[])))
);


--
-- Name: datasets_dataset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.datasets ALTER COLUMN dataset_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datasets_dataset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: diagnosis_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diagnosis_answers (
                                          answer boolean NOT NULL,
                                          score integer NOT NULL,
                                          answer_id bigint NOT NULL,
                                          diagnosis_id bigint NOT NULL,
                                          question_code character varying(30) NOT NULL
);


--
-- Name: diagnosis_answers_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diagnosis_answers ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnosis_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: fairness_group_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fairness_group_stats (
                                             actual_default_rate numeric(10,4),
                                             approval_rate numeric(10,4),
                                             auc numeric(6,4),
                                             fn integer NOT NULL,
                                             fp integer NOT NULL,
                                             n integer NOT NULL,
                                             tn integer NOT NULL,
                                             tp integer NOT NULL,
                                             audit_id bigint NOT NULL,
                                             group_stat_id bigint NOT NULL,
                                             attribute character varying(50) NOT NULL,
                                             group_name character varying(100) NOT NULL
);


--
-- Name: fairness_group_stats_group_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fairness_group_stats ALTER COLUMN group_stat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fairness_group_stats_group_stat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: fairness_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fairness_results (
                                         threshold numeric(10,4) NOT NULL,
                                         value numeric(10,4) NOT NULL,
                                         audit_id bigint NOT NULL,
                                         result_id bigint NOT NULL,
                                         status character varying(20) NOT NULL,
                                         metric_code character varying(30) NOT NULL,
                                         attribute character varying(50) NOT NULL,
                                         note character varying(255),
                                         CONSTRAINT fairness_results_metric_code_check CHECK (((metric_code)::text = ANY ((ARRAY['DEMOGRAPHIC_PARITY'::character varying, 'EQUALIZED_ODDS'::character varying, 'EQUAL_OPPORTUNITY'::character varying, 'PROPORTIONAL_PARITY'::character varying, 'FPR_PARITY'::character varying, 'FDR_PARITY'::character varying, 'FOR_PARITY'::character varying])::text[]))),
                                         CONSTRAINT fairness_results_status_check CHECK (((status)::text = ANY ((ARRAY['PASS'::character varying, 'REVIEW'::character varying, 'FAIL'::character varying])::text[])))
);


--
-- Name: fairness_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fairness_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fairness_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: health_check; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_check (
                                     created_at timestamp(6) without time zone NOT NULL,
                                     id bigint NOT NULL,
                                     updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: health_check_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_check ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: law_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.law_articles (
                                     effective_date date NOT NULL,
                                     revision_date date,
                                     article_id bigint NOT NULL,
                                     article_no character varying(30) NOT NULL,
                                     law_name character varying(100) NOT NULL,
                                     content text NOT NULL,
                                     summary text,
                                     embedding public.vector(1536)
);


--
-- Name: law_articles_article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.law_articles ALTER COLUMN article_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.law_articles_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: law_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.law_revisions (
                                      revised_at date NOT NULL,
                                      collected_at timestamp(6) without time zone NOT NULL,
                                      revision_id bigint NOT NULL,
                                      revision_type character varying(20) NOT NULL,
                                      source character varying(50) NOT NULL,
                                      title character varying(200) NOT NULL,
                                      CONSTRAINT law_revisions_revision_type_check CHECK (((revision_type)::text = ANY ((ARRAY['AMENDMENT'::character varying, 'NOTICE'::character varying, 'GUIDELINE_CHANGE'::character varying])::text[])))
);


--
-- Name: law_revisions_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.law_revisions ALTER COLUMN revision_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.law_revisions_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
                                      is_read boolean NOT NULL,
                                      audit_id bigint,
                                      notification_id bigint NOT NULL,
                                      revision_id bigint,
                                      sent_at timestamp(6) without time zone NOT NULL,
                                      user_id bigint NOT NULL,
                                      channel character varying(20) NOT NULL,
                                      notif_type character varying(20) NOT NULL,
                                      status character varying(20) NOT NULL,
                                      CONSTRAINT ck_notifications_type_reference CHECK (((((notif_type)::text = 'LAW_REVISION'::text) AND (revision_id IS NOT NULL) AND (audit_id IS NULL)) OR (((notif_type)::text = 'REAUDIT_RECOMMEND'::text) AND (audit_id IS NOT NULL) AND (revision_id IS NULL)) OR (((notif_type)::text = 'AUDIT_COMPLETE'::text) AND (audit_id IS NOT NULL) AND (revision_id IS NULL)) OR (((notif_type)::text = 'AUDIT_FAILED'::text) AND (audit_id IS NOT NULL) AND (revision_id IS NULL)))),
                                      CONSTRAINT notifications_channel_check CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'IN_APP'::character varying])::text[]))),
                                      CONSTRAINT notifications_status_check CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: objections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.objections (
                                   approved_at timestamp(6) without time zone,
                                   approver_id bigint,
                                   created_at timestamp(6) without time zone NOT NULL,
                                   delivered_at timestamp(6) without time zone,
                                   model_id bigint,
                                   objection_id bigint NOT NULL,
                                   submitted_at timestamp(6) without time zone NOT NULL,
                                   updated_at timestamp(6) without time zone NOT NULL,
                                   decision character varying(20),
                                   objection_no character varying(20) NOT NULL,
                                   status character varying(20) NOT NULL,
                                   customer_name character varying(50) NOT NULL,
                                   case_type character varying(100) NOT NULL,
                                   recipient_email character varying(100),
                                   title character varying(200) NOT NULL,
                                   content text NOT NULL,
                                   draft_content text,
                                   shap_evidence text,
                                   staff_note text,
                                   CONSTRAINT objections_decision_check CHECK (((decision)::text = ANY ((ARRAY['REJECT_MAINTAIN'::character varying, 'REEXAMINATION'::character varying])::text[]))),
                                   CONSTRAINT objections_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'REVIEWING'::character varying, 'APPROVED'::character varying, 'DELIVERED'::character varying])::text[])))
);


--
-- Name: objections_objection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.objections ALTER COLUMN objection_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.objections_objection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: pre_diagnoses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pre_diagnoses (
                                      condition_met boolean NOT NULL,
                                      group_a_score integer NOT NULL,
                                      group_b_score integer NOT NULL,
                                      total_score integer NOT NULL,
                                      created_at timestamp(6) without time zone NOT NULL,
                                      diagnosis_id bigint NOT NULL,
                                      model_id bigint,
                                      updated_at timestamp(6) without time zone NOT NULL,
                                      user_id bigint NOT NULL,
                                      result character varying(20) NOT NULL,
                                      report_path character varying(255),
                                      CONSTRAINT pre_diagnoses_result_check CHECK (((result)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'HIGH_IMPACT'::character varying, 'NEEDS_QUANTITATIVE'::character varying, 'NOT_APPLICABLE'::character varying])::text[])))
);


--
-- Name: pre_diagnoses_diagnosis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pre_diagnoses ALTER COLUMN diagnosis_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pre_diagnoses_diagnosis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: report_narratives; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_narratives (
                                          narrative_id bigint NOT NULL,
                                          created_at timestamp(6) without time zone NOT NULL,
                                          updated_at timestamp(6) without time zone NOT NULL,
                                          content text NOT NULL,
                                          display_order integer NOT NULL,
                                          report_type character varying(30) NOT NULL,
                                          section_key character varying(50) NOT NULL,
                                          title character varying(200) NOT NULL,
                                          audit_id bigint NOT NULL,
                                          CONSTRAINT report_narratives_report_type_check CHECK (((report_type)::text = ANY ((ARRAY['XAI_REPORT'::character varying, 'BIAS_REPORT'::character varying, 'HIGH_IMPACT_REPORT'::character varying, 'COMPLIANCE_VERDICT'::character varying, 'IMPROVEMENT_GUIDE'::character varying, 'FINAL_AUDIT_REPORT'::character varying])::text[])))
);


--
-- Name: report_narratives_narrative_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_narratives ALTER COLUMN narrative_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_narratives_narrative_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
                                version integer NOT NULL,
                                audit_id bigint NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                report_id bigint NOT NULL,
                                updated_at timestamp(6) without time zone NOT NULL,
                                format character varying(20) NOT NULL,
                                report_type character varying(20) NOT NULL,
                                status character varying(20) NOT NULL,
                                file_path character varying(255) NOT NULL,
                                CONSTRAINT reports_format_check CHECK (((format)::text = ANY ((ARRAY['PDF'::character varying, 'WORD'::character varying, 'HTML'::character varying])::text[]))),
                                CONSTRAINT reports_report_type_check CHECK (((report_type)::text = ANY ((ARRAY['XAI_REPORT'::character varying, 'BIAS_REPORT'::character varying, 'HIGH_IMPACT_REPORT'::character varying, 'COMPLIANCE_VERDICT'::character varying, 'IMPROVEMENT_GUIDE'::character varying, 'FINAL_AUDIT_REPORT'::character varying])::text[]))),
                                CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['GENERATING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: self_check_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.self_check_answers (
                                           audit_id bigint NOT NULL,
                                           check_id bigint NOT NULL,
                                           item_code character varying(30) NOT NULL,
                                           answer_value character varying(10) DEFAULT 'NO'::character varying NOT NULL,
                                           CONSTRAINT self_check_answers_answer_value_check CHECK (((answer_value)::text = ANY ((ARRAY['YES'::character varying, 'NO'::character varying, 'NA'::character varying])::text[])))
);


--
-- Name: self_check_answers_check_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.self_check_answers ALTER COLUMN check_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.self_check_answers_check_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: shap_feature_importances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shap_feature_importances (
                                                 contribution_ratio numeric(10,6),
                                                 is_sensitive boolean NOT NULL,
                                                 mean_abs_shap numeric(14,6) NOT NULL,
                                                 mean_signed_shap numeric(14,6) NOT NULL,
                                                 rank integer NOT NULL,
                                                 audit_id bigint NOT NULL,
                                                 importance_id bigint NOT NULL,
                                                 direction character varying(20),
                                                 sensitive_group character varying(50),
                                                 feature character varying(100) NOT NULL
);


--
-- Name: shap_feature_importances_importance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shap_feature_importances ALTER COLUMN importance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shap_feature_importances_importance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              audit_complete_alert_enabled boolean DEFAULT true NOT NULL,
                              is_active boolean NOT NULL,
                              law_email_enabled boolean DEFAULT true NOT NULL,
                              reaudit_alert_enabled boolean NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              deleted_at timestamp(6) without time zone,
                              last_login_at timestamp(6) without time zone,
                              updated_at timestamp(6) without time zone NOT NULL,
                              user_id bigint NOT NULL,
                              role character varying(20) NOT NULL,
                              name character varying(50) NOT NULL,
                              email character varying(100) NOT NULL,
                              institution character varying(100) NOT NULL,
                              password_hash character varying(255) NOT NULL,
                              audit_fail_alert_enabled boolean DEFAULT true NOT NULL,
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'AUDITOR'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: xai_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.xai_results (
                                    threshold numeric(10,4) NOT NULL,
                                    value numeric(10,4) NOT NULL,
                                    audit_id bigint NOT NULL,
                                    result_id bigint NOT NULL,
                                    status character varying(20) NOT NULL,
                                    metric_code character varying(30) NOT NULL,
                                    CONSTRAINT xai_results_metric_code_check CHECK (((metric_code)::text = ANY ((ARRAY['SENSITIVE_CONTRIB'::character varying, 'GLOBAL_STABILITY'::character varying, 'FIDELITY'::character varying])::text[]))),
                                    CONSTRAINT xai_results_status_check CHECK (((status)::text = ANY ((ARRAY['PASS'::character varying, 'WARNING'::character varying, 'REVIEW'::character varying])::text[])))
);


--
-- Name: xai_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.xai_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xai_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: ai_models ai_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_pkey PRIMARY KEY (model_id);


--
-- Name: audit_law_mappings audit_law_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_law_mappings
    ADD CONSTRAINT audit_law_mappings_pkey PRIMARY KEY (mapping_id);


--
-- Name: audits audits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT audits_pkey PRIMARY KEY (audit_id);


--
-- Name: board_comments board_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_comments
    ADD CONSTRAINT board_comments_pkey PRIMARY KEY (comment_id);


--
-- Name: board_post_attachments board_post_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_post_attachments
    ADD CONSTRAINT board_post_attachments_pkey PRIMARY KEY (attachment_id);


--
-- Name: board_posts board_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_posts
    ADD CONSTRAINT board_posts_pkey PRIMARY KEY (post_id);


--
-- Name: chat_conversations chat_conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversations
    ADD CONSTRAINT chat_conversations_pkey PRIMARY KEY (conversation_id);


--
-- Name: chat_message_citations chat_message_citations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message_citations
    ADD CONSTRAINT chat_message_citations_pkey PRIMARY KEY (citation_id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (message_id);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (dataset_id);


--
-- Name: diagnosis_answers diagnosis_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis_answers
    ADD CONSTRAINT diagnosis_answers_pkey PRIMARY KEY (answer_id);


--
-- Name: fairness_group_stats fairness_group_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_group_stats
    ADD CONSTRAINT fairness_group_stats_pkey PRIMARY KEY (group_stat_id);


--
-- Name: fairness_results fairness_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_results
    ADD CONSTRAINT fairness_results_pkey PRIMARY KEY (result_id);


--
-- Name: health_check health_check_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_check
    ADD CONSTRAINT health_check_pkey PRIMARY KEY (id);


--
-- Name: law_articles law_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.law_articles
    ADD CONSTRAINT law_articles_pkey PRIMARY KEY (article_id);


--
-- Name: law_revisions law_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.law_revisions
    ADD CONSTRAINT law_revisions_pkey PRIMARY KEY (revision_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: objections objections_objection_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objections
    ADD CONSTRAINT objections_objection_no_key UNIQUE (objection_no);


--
-- Name: objections objections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objections
    ADD CONSTRAINT objections_pkey PRIMARY KEY (objection_id);


--
-- Name: pre_diagnoses pre_diagnoses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pre_diagnoses
    ADD CONSTRAINT pre_diagnoses_pkey PRIMARY KEY (diagnosis_id);


--
-- Name: report_narratives report_narratives_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_narratives
    ADD CONSTRAINT report_narratives_pkey PRIMARY KEY (narrative_id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (report_id);


--
-- Name: self_check_answers self_check_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_check_answers
    ADD CONSTRAINT self_check_answers_pkey PRIMARY KEY (check_id);


--
-- Name: shap_feature_importances shap_feature_importances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shap_feature_importances
    ADD CONSTRAINT shap_feature_importances_pkey PRIMARY KEY (importance_id);


--
-- Name: audit_law_mappings uk_audit_law_mappings_audit_article; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_law_mappings
    ADD CONSTRAINT uk_audit_law_mappings_audit_article UNIQUE (audit_id, article_id);


--
-- Name: diagnosis_answers uk_diagnosis_answers_diagnosis_question; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis_answers
    ADD CONSTRAINT uk_diagnosis_answers_diagnosis_question UNIQUE (diagnosis_id, question_code);


--
-- Name: fairness_group_stats uk_fairness_group_stats_audit_attribute_group; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_group_stats
    ADD CONSTRAINT uk_fairness_group_stats_audit_attribute_group UNIQUE (audit_id, attribute, group_name);


--
-- Name: fairness_results uk_fairness_results_audit_metric_attribute; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_results
    ADD CONSTRAINT uk_fairness_results_audit_metric_attribute UNIQUE (audit_id, metric_code, attribute);


--
-- Name: self_check_answers uk_self_check_answers_audit_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_check_answers
    ADD CONSTRAINT uk_self_check_answers_audit_item UNIQUE (audit_id, item_code);


--
-- Name: shap_feature_importances uk_shap_feature_importances_audit_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shap_feature_importances
    ADD CONSTRAINT uk_shap_feature_importances_audit_rank UNIQUE (audit_id, rank);


--
-- Name: xai_results uk_xai_results_audit_metric_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xai_results
    ADD CONSTRAINT uk_xai_results_audit_metric_code UNIQUE (audit_id, metric_code);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: xai_results xai_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xai_results
    ADD CONSTRAINT xai_results_pkey PRIMARY KEY (result_id);


--
-- Name: board_comments fk2kd7d3brq5ea33jnqxrdnpb71; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_comments
    ADD CONSTRAINT fk2kd7d3brq5ea33jnqxrdnpb71 FOREIGN KEY (post_id) REFERENCES public.board_posts(post_id);


--
-- Name: chat_conversations fk40okueacd48n616c3r1nvjwpr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversations
    ADD CONSTRAINT fk40okueacd48n616c3r1nvjwpr FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: chat_conversations fk5ua5q54udnljdtinrv7y4kusn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversations
    ADD CONSTRAINT fk5ua5q54udnljdtinrv7y4kusn FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: self_check_answers fk64lq8rgepw0yffacfsge5lap6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_check_answers
    ADD CONSTRAINT fk64lq8rgepw0yffacfsge5lap6 FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: objections fk6tyt3tlir8ug2cjde1q4ujs73; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objections
    ADD CONSTRAINT fk6tyt3tlir8ug2cjde1q4ujs73 FOREIGN KEY (model_id) REFERENCES public.ai_models(model_id);


--
-- Name: audits fk7p2ot7k3j09ueu0n32wa9f79d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fk7p2ot7k3j09ueu0n32wa9f79d FOREIGN KEY (dataset_id) REFERENCES public.datasets(dataset_id);


--
-- Name: board_post_attachments fk9dmfoba2gtigffiwm5mn2aclq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_post_attachments
    ADD CONSTRAINT fk9dmfoba2gtigffiwm5mn2aclq FOREIGN KEY (post_id) REFERENCES public.board_posts(post_id);


--
-- Name: xai_results fk9ivb7tdpwphmokwm2xxghycb1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.xai_results
    ADD CONSTRAINT fk9ivb7tdpwphmokwm2xxghycb1 FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: pre_diagnoses fk9wplrtlmcsvd3rcta2m5fkwfq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pre_diagnoses
    ADD CONSTRAINT fk9wplrtlmcsvd3rcta2m5fkwfq FOREIGN KEY (model_id) REFERENCES public.ai_models(model_id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: board_comments fkabl56q9asd677yg8wl1flgv3h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_comments
    ADD CONSTRAINT fkabl56q9asd677yg8wl1flgv3h FOREIGN KEY (author_id) REFERENCES public.users(user_id);


--
-- Name: audits fkai7wp279jv0j3y5bb3u59nhsg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fkai7wp279jv0j3y5bb3u59nhsg FOREIGN KEY (model_id) REFERENCES public.ai_models(model_id);


--
-- Name: board_posts fkcn406wq798n82q74f2emwkrac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_posts
    ADD CONSTRAINT fkcn406wq798n82q74f2emwkrac FOREIGN KEY (author_id) REFERENCES public.users(user_id);


--
-- Name: audit_law_mappings fkddv0me131xf3n8v7l2hnc2cyw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_law_mappings
    ADD CONSTRAINT fkddv0me131xf3n8v7l2hnc2cyw FOREIGN KEY (article_id) REFERENCES public.law_articles(article_id);


--
-- Name: audits fkdmn1iv1ewrg5esr07wcu0txq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fkdmn1iv1ewrg5esr07wcu0txq FOREIGN KEY (validation_dataset_id) REFERENCES public.datasets(dataset_id);


--
-- Name: datasets fkgja27y1pb0o7ve6a85f8dafi2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT fkgja27y1pb0o7ve6a85f8dafi2 FOREIGN KEY (model_id) REFERENCES public.ai_models(model_id);


--
-- Name: ai_models fkhsybatompa9ga3gw320ufoxv9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT fkhsybatompa9ga3gw320ufoxv9 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: fairness_results fki4a2abl0rdni99n9k2xdumb65; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_results
    ADD CONSTRAINT fki4a2abl0rdni99n9k2xdumb65 FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: diagnosis_answers fkiurxmjs68letxijxnh95ex1xl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis_answers
    ADD CONSTRAINT fkiurxmjs68letxijxnh95ex1xl FOREIGN KEY (diagnosis_id) REFERENCES public.pre_diagnoses(diagnosis_id);


--
-- Name: objections fkjcef6t1bor1hppg6659ptukjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objections
    ADD CONSTRAINT fkjcef6t1bor1hppg6659ptukjm FOREIGN KEY (approver_id) REFERENCES public.users(user_id);


--
-- Name: shap_feature_importances fkk7po58vg6vnr3rnos9tpu1ary; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shap_feature_importances
    ADD CONSTRAINT fkk7po58vg6vnr3rnos9tpu1ary FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: audits fkkf5h7txhgapq8yj144w5rx2pp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audits
    ADD CONSTRAINT fkkf5h7txhgapq8yj144w5rx2pp FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: report_narratives fkklyuxsibhdoeqph5roui1vlxi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_narratives
    ADD CONSTRAINT fkklyuxsibhdoeqph5roui1vlxi FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: chat_message_citations fklxgh9fqjrxapfusf5li1wi398; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message_citations
    ADD CONSTRAINT fklxgh9fqjrxapfusf5li1wi398 FOREIGN KEY (message_id) REFERENCES public.chat_messages(message_id);


--
-- Name: notifications fkmupxh88dv2taxafkf7u3hyby; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkmupxh88dv2taxafkf7u3hyby FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: notifications fknp4k90ewjn90sj62txrrtciv7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fknp4k90ewjn90sj62txrrtciv7 FOREIGN KEY (revision_id) REFERENCES public.law_revisions(revision_id);


--
-- Name: reports fkobisxdotngpu2mj1rlgcey7fu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkobisxdotngpu2mj1rlgcey7fu FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: pre_diagnoses fkox8s9778wwupr2n2hhmobh6n8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pre_diagnoses
    ADD CONSTRAINT fkox8s9778wwupr2n2hhmobh6n8 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: audit_law_mappings fkq810ybkwfw2if2ju2kfqs64oe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_law_mappings
    ADD CONSTRAINT fkq810ybkwfw2if2ju2kfqs64oe FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- Name: chat_messages fkqgkanrr90j46564w4ww63jcna; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkqgkanrr90j46564w4ww63jcna FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(conversation_id);


--
-- Name: fairness_group_stats fks9gq55s6lmxiamqkp3nwi71ay; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fairness_group_stats
    ADD CONSTRAINT fks9gq55s6lmxiamqkp3nwi71ay FOREIGN KEY (audit_id) REFERENCES public.audits(audit_id);


--
-- PostgreSQL database dump complete
--